# Problem 1 Array Creation

In [1]:


import numpy as np

#1 Empty array 
empty_array= np.empty((2,2))
print(empty_array)
print()
#2 One array
one_array = np.ones((4,2))
print(one_array)
print()
#3 Full array with 7
full_array = np.full((2,2),7)
print(full_array)
print()
#4 Zero array
zero_array = np.zeros((2,2))
print(zero_array)
print()
#5  Ones array with 2 by 2 matrix
ones_array =np.ones((2,2))
print(ones_array)
print()
#6
new_list =[1,2,3,4]
new = np.array(new_list)
print(new)



[[3.00392950e-307 3.11524600e-307]
 [2.44776968e-307 8.62249648e-308]]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[7 7]
 [7 7]]

[[0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]]

[1 2 3 4]


# Problem 2 Array Manipulation: Numerical Ranges and Array indexing:

In [2]:
 
import numpy as np 
#1 array arrange from 10 to 48
arrange_array = np.arange(10,49)
print(arrange_array)
print()
#2  reshape into 3by 3 matrix
array = np.array([[0, 1, 2], [3, 4, 5],[6,7,8]])
reshape_array = array.reshape(3,3)
print(reshape_array)
print()
#3 Identity matrix
identity = np.eye(3)
print(identity)
print()
#4
random_array =np.random.random(30)
total = random_array.mean()
print(total)
print()
#5  Min max value of 10 by 10 random matrix
ran_array = np.random.random((10,10))
min_val = ran_array.min()
max_val = ran_array.max()
print(ran_array)
print("Min value is:",min_val)
print("Max value is:",max_val)
print()
#6
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)
print()
#7  reversing the given array
n_list =[1,2,0,0,4,0]
new = np.array(n_list)
reversed_array = new[::-1]
print(reversed_array)
print()


#creating 5 by 5 matrix with value 0 
arr = np.zeros((5,5), dtype=int)


arr[0, :] = 1 # assigning first row value 1
arr[4, :] = 1 #assigning last row value 1
arr[:, 0] = 1 # assigning first row all columns with val 1
arr[:, 4] = 1 #assigning right corner last row all column with val 1

print("2D Array with Border 1 and Inside 0:")
print(arr)
print()
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[::2, ::2] = 1  
checkerboard[1::2, 1::2] = 1  

print("8x8 Checkerboard Matrix:")
print(checkerboard)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

0.5404731602574365

[[0.44784916 0.4088352  0.82223757 0.61844042 0.53361671 0.23577634
  0.10611308 0.39319947 0.2091343  0.47604685]
 [0.73866759 0.67826066 0.67492527 0.30865308 0.08423604 0.35228259
  0.57921328 0.23479219 0.81273002 0.8404587 ]
 [0.02178735 0.61729248 0.53685628 0.13379099 0.55953274 0.62420231
  0.35299758 0.90756136 0.6251095  0.63229316]
 [0.11706159 0.07694483 0.72428606 0.96374103 0.0944699  0.70201025
  0.13999067 0.68486767 0.12749069 0.77707903]
 [0.05449313 0.05128936 0.7586456  0.6168841  0.16922333 0.68260752
  0.31649123 0.22092726 0.14264951 0.70758075]
 [0.83165559 0.95048375 0.0383742  0.08455605 0.28679146 0.58109196
  0.9432988  0.22188716 0.88229159 0.23779541]
 [0.85310842 0.82149531 0.32265605 0.75343969 0.75086907 0.64639348
  0.48082218 0.4598781  0.41669542

# Problem 3 Array Operations

In [3]:


import numpy as np


x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
#1
addArray = x + y;
print("Adding two arrays:")
print(addArray);
print()
#2
subArray = x-y;
print("sub two arrray:")
print(subArray)
print()
#3
mulArray = 2*x;
print("Multiply array:")
print(mulArray)
print()
#4
sqArray = np.square(x)
sqY = np.square(y)
sqV = np.square(v)
sqW = np.square(w)
print("Square of x,y,v,w is:")
print(sqArray)
print()
print(sqY)
print()
print(sqV)
print()
print(sqW)
print()
dotX = np.dot(v,w)
dotY = np.dot(x,v)
dotZ = np.dot(x,y)
print("Dot product between v and w:")
print(dotX)
print()
print("Dot product between x and v:")
print(dotY)
print()
print("Dot product between x and y:")
print(dotZ)
print()
#merge
concaX= np.concatenate((x,y), axis = 0)
concaY = np.vstack((v,w))
print("Concatenate :")
print(concaX)
print()
print(concaY)
print()
# concaZ= np.concatenate((x,v), axis = 0) all inputs must have same number of dimenstions.
# print(concaZ)

Adding two arrays:
[[ 6  8]
 [10 13]]

sub two arrray:
[[-4 -4]
 [-4 -3]]

Multiply array:
[[ 2  4]
 [ 6 10]]

Square of x,y,v,w is:
[[ 1  4]
 [ 9 25]]

[[25 36]
 [49 64]]

[ 81 100]

[121 144]

Dot product between v and w:
219

Dot product between x and v:
[29 77]

Dot product between x and y:
[[19 22]
 [50 58]]

Concatenate :
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

[[ 9 10]
 [11 12]]



# Problem 4 Matrix Operation

In [4]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);
# newArr = np.array([[8, -4],[-7,3]])
# inverseA = 1/(24-28)*newArr
inverseA = np.linalg.inv(A)
result = np.dot(A,inverseA)
# inverseX = A *inverseA
# print(inverseA)
# print()
print(result)
print()
identity = np.eye(A.shape[0])
print("A.A^-1 = I :")
print(np.allclose(result,identity))
print()
mulA = np.dot(A,B)
mulB = np.dot(B,A)
print("AB == BA:")
print(np.allclose(mulA,mulB))
print()
C = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
D = np.array([-1, -3, 9])
inverseC = np.linalg.inv(C)
result_cd= np.dot(inverseC, D)
print(result_cd)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

A.A^-1 = I :
True

AB == BA:
False

[ 2.  1. -2.]


# Experiment tasks

### 1.Element-wise Addition

### Using python list

In [5]:
import time

def add_lists(list1, list2):
    
    result = []
    for i in range(len(list1)):
        result.append(list1[i] + list2[i])
    return result

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i  for i in range(1000000)]

# Measure the time taken
start_time = time.time()
result = add_lists(list1, list2)
end_time = time.time()

# Print the time taken
print("Time taken:", end_time - start_time, "seconds")

Time taken: 0.046346187591552734 seconds


### Using numpy array

In [6]:
import numpy as np
import time

aar1 = np.arange(0, 1000000)
aar2 = np.arange(0,1000000)

start_time = time.time()
result = aar1 + aar2
end_time = time.time()
print("Time taken:",end_time-start_time, " seconds")

Time taken: 0.009419918060302734  seconds


# 2.Element-wise multiplication

### Python  list

In [7]:
import time

def add_lists(list1, list2):
    
    result = []
    for i in range(len(list1)):
        result.append(list1[i] * list2[i])
    return result

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i  for i in range(1000000)]

# Measure the time taken
start_time = time.time()
result = add_lists(list1, list2)
end_time = time.time()

# Print the time taken
print("Time taken:", end_time - start_time, "seconds")

Time taken: 0.0475921630859375 seconds


### Numpy array

In [8]:
import numpy as np
import time

aar1 = np.arange(0, 1000000)
aar2 = np.arange(0,1000000)

start_time = time.time()
result = aar1 * aar2
end_time = time.time()
print("Time taken:",end_time-start_time, " seconds")

Time taken: 0.011261463165283203  seconds


# Dot product

### Python list

In [9]:
import time

def add_lists(list1, list2):
    
    result = []
    for i in range(len(list1)):
        result.append(list1[i] * list2[i])
    return result

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i  for i in range(1000000)]

# Measure the time taken
start_time = time.time()
result = add_lists(list1, list2)
end_time = time.time()

# Print the time taken
print("Time taken:", end_time - start_time, "seconds")

Time taken: 0.04613542556762695 seconds


### Numpy array

In [10]:
import numpy as np
import time

aar1 = np.arange(0, 1000000)
aar2 = np.arange(0,1000000)

start_time = time.time()
result = np.dot(aar1,aar2)
end_time = time.time()
print("Time taken:",end_time-start_time, " seconds")

Time taken: 0.008627891540527344  seconds


In [ ]:
import random
import time

# Matrix size
n = 1000

# Generate two random 1000x1000 matrices
matrix_a = [[random.randint(0, 10) for _ in range(n)] for _ in range(n)]
matrix_b = [[random.randint(0, 10) for _ in range(n)] for _ in range(n)]

# Initialize the result matrix with zeros
result = [[0] * n for _ in range(n)]

# Perform matrix multiplication and measure the time taken
start_time = time.time()

for i in range(n):
    for j in range(n):
        for k in range(n):
            result[i][j] += matrix_a[i][k] * matrix_b[k][j]

end_time = time.time()

# Print the time taken
time_taken = end_time - start_time
print(time_taken)


In [ ]:
import numpy as np
import time

# Create two NumPy arrays of size 1000x1000
matrix1 = np.random.rand(1000, 1000)
matrix2 = np.random.rand(1000, 1000)

# Measure the time taken
start_time = time.time()
product = np.dot(matrix1, matrix2)
end_time = time.time()

# Print the time taken
print("Time taken:", end_time - start_time, "seconds")